### ISSUE TITLE
Installing error 

### ISSUE THREAD

**Issue by rhj1993119** [ajxa/GBMDeconvoluteR#2]
Hi I am trying to install the package on my local computer. 
However, I am getting an error message as below : 

Error: Failed to install 'unknown package' from GitHub:
HTTP error 404.
Not Found

Did you spell the repo owner (`ajxa`) and repo name (`GBMDeconvoluteR`) correctly?
- If spelling is correct, check that you have the required permissions to access the repo.

Do you have any idea to solve this error? 
thanks

**Comment by ajxa** [comment]
Hi rhj1993119,

The reason you're getting an error is because this repo doesn't contain code for an R package, rather it contains the code that is necessary to produce and run a shiny application. 

If you wish to run this application on your local machine, this can be easily be done by running first forking this repository and the using the `shiny::runGitHub()` function from the shiny R package.

**Comment by ajxa** [comment]
Hi rhj1993119,

I just wanted to check if you managed to successfully run a local version of this application? If you did, are you happy with this issue being closed?

Thank You.
